### ISSUE TITLE
Short-Circuit Manifest Application / Pod Health Checks if not provided

### ISSUE THREAD

**Issue by MMartyn** [mumoshu/terraform-provider-eksctl#3]
If no manifests are provided we could skip the attempt to apply them. Same for the pod health checks.

**Comment by MMartyn** [comment]
Possibly something like so:

https://github.com/mumoshu/terraform-provider-eksctl/blob/master/pkg/resource/cluster/cluster.go#L40
```go
if len(cluster.CheckPodsReadinessConfigs) == 0 {
  return nil
}
```
https://github.com/mumoshu/terraform-provider-eksctl/blob/master/pkg/resource/cluster/cluster.go#L93

**Comment by mumoshu** [comment]
@MMartyn Thanks! That makes senes. It's fixed in master now.
