### ISSUE TITLE
Licence - Open source or not?

### ISSUE THREAD

**Issue by saurabh-arios** [mumoshu/terraform-provider-eksctl#37]
Hi @mumoshu I was exploring the possibility of eksctl within terraform and I came across your awesome project. It looks good but I am not sure, I can freely use it, as this repo doesn't mention any type of license which implies this project is restricted for anyone without your consent. Please check this [link](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository) and apply an oss license as you deem fit or let us know if this project is not supposed to be an oss.

**Comment by mumoshu** [comment]
@saurabh-arios Hey! I somehow forgot to add the [LICENSE](https://github.com/mumoshu/terraform-provider-eksctl/blob/master/LICENSE) file! It's Apace License 2 and is definitely an open-source project.
