### ISSUE TITLE
Add ability to specify timeout

### ISSUE THREAD

**Issue by ruckc** [mumoshu/terraform-provider-eksctl#52]
For some reason everytime I create a nodegroup, with eksctl directly or via terraform, the creation hits eksctl's timeout and eksctl rolls it back.  Can you expose the timeout parameter?

**Comment by mumoshu** [comment]
@ruckc Hey! We're trying to expose it via resource/provider config in https://github.com/mumoshu/terraform-provider-eksctl/pull/51

**Comment by ruckc** [comment]
great.  awesome.
