### ISSUE TITLE
GPG key expired

### ISSUE THREAD

**Issue by benjiro** [mumoshu/terraform-provider-eksctl#65]
The release process is currently broken due to the gpg being expired.

![image](https://user-images.githubusercontent.com/2031163/192430915-fb7412c3-8bd4-4f4a-a081-25118473c755.png)

**Comment by benjiro** [comment]
@mumoshu Are you able to regenerate the GPG key and update the secrets plus the gpg key in terraforms registry is needed. 🙏🏻

**Comment by mumoshu** [comment]
Will do! Thanks for reporting

**Comment by benjiro** [comment]
Thanks @mumoshu let me know when your done and ill retrigger the release

**Comment by mumoshu** [comment]
@benjiro Updated GitHub secrets and also re-registered the new GPG pub key to Terraform Registry. It should work now!

**Comment by benjiro** [comment]
Thanks @mumoshu
