### ISSUE TITLE
Gitops example

### ISSUE THREAD

**Issue by bainss** [mumoshu/terraform-provider-eksctl#8]
Is there an example of how you would apply gitops via fluxCD so that terraform can create the cluster unattended?

**Comment by mumoshu** [comment]
@bainss Hey! Sorry for the delayed response. Yes - see examples like https://github.com/mumoshu/terraform-provider-eksctl/blob/cb513f57f5ce542745c05f0241cb9643bfbdbf09/examples/productionsetup-alb/testdata/01-bootstrap/main.tf#L132-L144

**Comment by benjiro** [comment]
Marking as resolved based on mumoshu response. Reopen if that example wasn't enough
